# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92c628eb9d088ba3f485c5d9ea6100a4228f05a2293827fff230724ed3be47e46f07d2636dbb9bf40a2fc2ff60c70b271f14b9ae4b7f0d1c723914fd9b803ed9

test:
  secret_key_base: 208e9c9b3dd2fa3929b30dae851dbd6a612c251dd7c2f7fd2efe4249708e745b8989d554b180c1553a939ba037e9a5cc237e67de0c0656a0698833b39eac9256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
